import type { Product } from '../types'

export const products: Product[] = [
  {
    id: 'ath-30',
    slug: 'atheryx-retatrutide-30mg',
    brand: 'atheryx',
    name: 'ATHERYX™ Retatrutide',
    peptide: 'Retatrutide Injection',
    dosage_mg: 30,
    doses_per_pen: 5,
    volume_ml: '0.6 mL',
    price_myr: 899,
    description: 'Advanced triple-agonist peptide therapy targeting GLP-1, GIP, and glucagon receptors. Designed for superior metabolic outcomes with precise multi-dose delivery system.',
    features: [
      'Triple-agonist mechanism (GLP-1/GIP/Glucagon)',
      'Precise multi-dose pen delivery',
      'Research-backed peptide formulation',
      'Premium pharmaceutical grade',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: [],
    lot: 'ATH250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ath-15',
    slug: 'atheryx-retatrutide-15mg',
    brand: 'atheryx',
    name: 'ATHERYX™ Retatrutide',
    peptide: 'Retatrutide Injection',
    dosage_mg: 15,
    doses_per_pen: 5,
    volume_ml: '0.6 mL',
    price_myr: 599,
    description: 'Entry-level triple-agonist peptide therapy with the same advanced mechanism in a starter dosage. Perfect for patients new to peptide therapy.',
    features: [
      'Triple-agonist mechanism (GLP-1/GIP/Glucagon)',
      'Starter dosage for new patients',
      'Precise multi-dose pen delivery',
      'Research-backed peptide formulation',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: [],
    lot: 'ATH250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ely-30',
    slug: 'elysion-tirzepatide-30mg',
    brand: 'elysion',
    name: 'ELYISION™ Tirzepatide',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 30,
    doses_per_pen: 5,
    volume_ml: '0.6 mL',
    price_myr: 799,
    description: 'Dual GIP/GLP-1 receptor agonist for powerful glycemic control and weight management. Clinically proven dual-agonist peptide in a convenient multi-dose pen.',
    features: [
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Clinically proven weight management',
      'Precise multi-dose pen delivery',
      'Premium pharmaceutical grade',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: [],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ely-25',
    slug: 'elysion-tirzepatide-25mg',
    brand: 'elysion',
    name: 'ELYISION™ Tirzepatide',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 25,
    doses_per_pen: 5,
    volume_ml: '0.6 mL',
    price_myr: 649,
    description: 'Starter dosage of the clinically proven dual-agonist peptide. Same powerful GIP/GLP-1 mechanism with a gentler entry point for new patients.',
    features: [
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Starter dosage for new patients',
      'Precise multi-dose pen delivery',
      'Clinically proven results',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: [],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
]
