import type { Product } from '../types'

export const products: Product[] = [
  // ─── ATHERYX (Retatrutide) ────────────────────────────
  {
    id: 'ath-10',
    slug: 'atheryx-retatrutide-10mg',
    brand: 'atheryx',
    name: 'ATHERYX™ Retatrutide',
    peptide: 'Retatrutide Injection',
    dosage_mg: 10,
    doses_per_pen: 5,
    per_dose_mg: 2,
    volume_ml: '0.6 mL',
    price_myr: 778,
    description: 'Entry-level triple-agonist peptide therapy. GLP-1, GIP, and glucagon receptor targeting for superior metabolic outcomes with precise multi-dose delivery system.',
    features: [
      'Triple-agonist mechanism (GLP-1/GIP/Glucagon)',
      'Starter dosage for new patients',
      'Precise multi-dose pen delivery',
      'Research-backed peptide formulation',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/atheryx-packaging.jpg'],
    lot: 'ATH250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ath-30',
    slug: 'atheryx-retatrutide-30mg',
    brand: 'atheryx',
    name: 'ATHERYX™ Retatrutide',
    peptide: 'Retatrutide Injection',
    dosage_mg: 30,
    doses_per_pen: 5,
    per_dose_mg: 6,
    volume_ml: '0.6 mL',
    price_myr: 1280,
    description: 'Advanced triple-agonist peptide therapy targeting GLP-1, GIP, and glucagon receptors. Designed for superior metabolic outcomes with precise multi-dose delivery system.',
    features: [
      'Triple-agonist mechanism (GLP-1/GIP/Glucagon)',
      'Precise multi-dose pen delivery',
      'Research-backed peptide formulation',
      'Premium pharmaceutical grade',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/atheryx-packaging.jpg'],
    lot: 'ATH250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ath-60',
    slug: 'atheryx-retatrutide-60mg',
    brand: 'atheryx',
    name: 'ATHERYX™ Retatrutide',
    peptide: 'Retatrutide Injection',
    dosage_mg: 60,
    doses_per_pen: 5,
    per_dose_mg: 12,
    volume_ml: '0.6 mL',
    price_myr: 1890,
    description: 'Maximum-strength triple-agonist peptide therapy. Full GLP-1, GIP, and glucagon receptor activation for patients requiring advanced metabolic support.',
    features: [
      'Triple-agonist mechanism (GLP-1/GIP/Glucagon)',
      'Maximum therapeutic dosage',
      'Precise multi-dose pen delivery',
      'Premium pharmaceutical grade',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/atheryx-packaging.jpg'],
    lot: 'ATH250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },

  // ─── ELYSION (Tirzepatide) — Standard Pens ────────────
  {
    id: 'ely-30',
    slug: 'elysion-tirzepatide-30mg',
    brand: 'elysion',
    name: 'ELYSION™ Tirzepatide',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 30,
    doses_per_pen: 5,
    per_dose_mg: 6,
    volume_ml: '0.6 mL',
    price_myr: 1088,
    description: 'Dual GIP/GLP-1 receptor agonist for powerful glycemic control and weight management. Clinically proven dual-agonist peptide in a convenient multi-dose pen.',
    features: [
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Clinically proven weight management',
      'Precise multi-dose pen delivery',
      'Premium pharmaceutical grade',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/elysion-packaging.jpg'],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ely-60',
    slug: 'elysion-tirzepatide-60mg',
    brand: 'elysion',
    name: 'ELYSION™ Tirzepatide',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 60,
    doses_per_pen: 5,
    per_dose_mg: 12,
    volume_ml: '0.6 mL',
    price_myr: 1518,
    description: 'Maximum-strength dual GIP/GLP-1 receptor agonist. Full therapeutic dosage for patients needing advanced glycemic control and significant weight management.',
    features: [
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Maximum therapeutic dosage',
      'Precise multi-dose pen delivery',
      'Premium pharmaceutical grade',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/elysion-packaging.jpg'],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },

  // ─── ELYSION GENERIC TIRZEPATIDE EZIPEN ──────────────
  {
    id: 'ely-ez12',
    slug: 'elysion-tirzepatide-ezipen-12-5mg',
    brand: 'elysion',
    name: 'ELYSION™ Tirzepatide Ezipen',
    display_name: 'ELYSION 12.5MG GENERIC TIRZEPATIDE EZIPEN',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 12.5,
    doses_per_pen: 5,
    per_dose_mg: 2.5,
    volume_ml: '0.6 mL',
    price_myr: 750,
    is_ezipen: true,
    description: 'Starter Ezipen with generic tirzepatide. Dual GIP/GLP-1 receptor agonist in a convenient pre-filled pen format.',
    features: [
      'Generic Tirzepatide formulation',
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Ezipen pre-filled delivery system',
      'Clinically proven weight management',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/elysion-packaging.jpg'],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ely-ez25',
    slug: 'elysion-tirzepatide-ezipen-25mg',
    brand: 'elysion',
    name: 'ELYSION™ Tirzepatide Ezipen',
    display_name: 'ELYSION 25MG GENERIC TIRZEPATIDE EZIPEN',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 25,
    doses_per_pen: 5,
    per_dose_mg: 5,
    volume_ml: '0.6 mL',
    price_myr: 988,
    is_ezipen: true,
    description: 'Popular dosage Ezipen with generic tirzepatide. Proven dual GIP/GLP-1 mechanism for effective weight management.',
    features: [
      'Generic Tirzepatide formulation',
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Ezipen pre-filled delivery system',
      '💰 RM200 discount for 3× social media weight loss sharing linked with our clinic',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/elysion-packaging.jpg'],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ely-ez50',
    slug: 'elysion-tirzepatide-ezipen-50mg',
    brand: 'elysion',
    name: 'ELYSION™ Tirzepatide Ezipen',
    display_name: 'ELYSION 50MG GENERIC TIRZEPATIDE EZIPEN',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 50,
    doses_per_pen: 5,
    per_dose_mg: 10,
    volume_ml: '0.6 mL',
    price_myr: 1418,
    is_ezipen: true,
    description: 'High-dosage Ezipen with generic tirzepatide. Full therapeutic GIP/GLP-1 dual agonism for significant weight management results.',
    features: [
      'Generic Tirzepatide formulation',
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Ezipen pre-filled delivery system',
      '💰 RM300 discount for 3× social media weight loss sharing linked with our clinic',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/elysion-packaging.jpg'],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
  {
    id: 'ely-ez75',
    slug: 'elysion-tirzepatide-ezipen-75mg',
    brand: 'elysion',
    name: 'ELYSION™ Tirzepatide Ezipen',
    display_name: 'ELYSION 75MG GENERIC TIRZEPATIDE EZIPEN',
    peptide: 'Tirzepatide Injection',
    dosage_mg: 75,
    doses_per_pen: 5,
    per_dose_mg: 15,
    volume_ml: '0.6 mL',
    price_myr: 1618,
    is_ezipen: true,
    description: 'Maximum-strength Ezipen with generic tirzepatide. Highest therapeutic GIP/GLP-1 dual agonism for advanced weight management.',
    features: [
      'Generic Tirzepatide formulation',
      'Dual-agonist mechanism (GIP/GLP-1)',
      'Ezipen pre-filled delivery system',
      'Maximum therapeutic dosage',
      'FDA Approved',
      'Sterile A — Rx Only',
    ],
    images: ['/elysion-packaging.jpg'],
    lot: 'ELY250701',
    exp: '2028-07',
    mal_number: 'MAL23056078XZ',
    fda_approved: true,
    stock: 100,
    active: true,
  },
]
